name: Run commands on list change
on:
 push:
   paths:
     - 'lists/main.txt'
     - 'lists/main-hosts.txt'
 pull_request:
   paths:
     - 'lists/main.txt'
     - 'lists/main-hosts.txt'
jobs:
 paths-filter:
   runs-on: ubuntu-latest
   outputs:
     main_txt_changed: ${{ steps.filter.outputs.main_txt_changed }}
     main_hosts_txt_changed: ${{ steps.filter.outputs.main_hosts_txt_changed }}
   steps:
   - uses: actions/checkout@v3
   - uses: dorny/paths-filter@v2
     id: filter
     with:
       filters: |
         main_txt_changed:
           - 'lists/main.txt'
         main_hosts_txt_changed:
           - 'lists/main-hosts.txt'
 build:
   needs: paths-filter
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Europe/Stockholm"

    - name: Run shell commands if main.txt has changed
      if: needs.paths-filter.outputs.main_txt_changed == 'true'
      run: |
        chmod +x tools/sort-filter.sh
        sh tools/sort-filter.sh

    - name: Run shell commands if main-hosts.txt has changed
      if: needs.paths-filter.outputs.main_hosts_txt_changed == 'true'
      run: |
        chmod +x tools/sort-hosts.sh
        sh tools/sort-hosts.sh

    - name: Commit changes (if any)
      run: |
        timestamp=$(date '+%Y%m%d_%H%M%S')
        git config user.name "GitHub-Actions"
        git config user.email "<>"
        git add Frellwits-Swedish-Filter.txt Frellwits-Swedish-Hosts-File.txt
        git commit -m "Update list ${timestamp}"
        git push
